// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyzRiIsW8CRqQwUvABdNogMWOo68vicdo',
    appId: '1:259824874046:web:301000e78cbabf1037576f',
    messagingSenderId: '259824874046',
    projectId: 'dine-a-tap',
    authDomain: 'dine-a-tap.firebaseapp.com',
    storageBucket: 'dine-a-tap.appspot.com',
    measurementId: 'G-FTF5FGN5DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvHeuiQa_KrCnizjQ1tNMoBorsVWGezY',
    appId: '1:259824874046:android:e44ba483d0e808d837576f',
    messagingSenderId: '259824874046',
    projectId: 'dine-a-tap',
    storageBucket: 'dine-a-tap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1EIuYzsmD7PkJ3Bh32j_ww5YStQ9R3w',
    appId: '1:259824874046:ios:997d3d88d82464bb37576f',
    messagingSenderId: '259824874046',
    projectId: 'dine-a-tap',
    storageBucket: 'dine-a-tap.appspot.com',
    iosBundleId: 'com.autoinnotech.dineATap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC1EIuYzsmD7PkJ3Bh32j_ww5YStQ9R3w',
    appId: '1:259824874046:ios:e33ce6e99149740f37576f',
    messagingSenderId: '259824874046',
    projectId: 'dine-a-tap',
    storageBucket: 'dine-a-tap.appspot.com',
    iosBundleId: 'com.autoinnotech.dineATap.RunnerTests',
  );
}
